In [2]:
import numpy as np
from sklearn.svm import SVC

In [3]:
X = np.array([[6,15],[8,12],[12,13],[10,10],[15,10],[13,8],[3,10],[7,7],[4,6],[8,4],[7,4],[10,2]])

In [4]:
y = np.array([1,1,1,1,1,1,-1,-1,-1,-1,-1,-1])

In [5]:
clf = SVC(C=1e5, kernel='linear')

In [6]:
clfmodel = clf.fit(X,y)

In [7]:
clfmodel.intercept_

array([-5.66666667])

In [8]:
clfmodel.coef_

array([[0.33333333, 0.33333333]])

In [9]:
clfmodel.support_vectors_

array([[ 7.,  7.],
       [10., 10.]])

In [10]:
clfmodel.decision_function

<bound method BaseSVC.decision_function of SVC(C=100000.0, kernel='linear')>

In [11]:
clfmodel.score(X,y)

1.0

In [12]:
clfmodel.probability


False